In [30]:
# %pip install torch
from transformers import pipeline
from nltk import sent_tokenize
import nltk
import torch
from glob import glob
import pandas as pd
import numpy as np

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/keshtech/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

# Load Model

In [3]:
model_name = "facebook/bart-large-mnli"
#device = 0 if torch.cuda.is_available() else "cpu"
device = 'cpu'

In [4]:
device

'cpu'

In [5]:
def load_model(device):
    classifier = pipeline("zero-shot-classification", model=model_name, device=device)
    return classifier

In [6]:
theme_classifier = load_model(device)

/home/keshtech/miniconda3/envs/series_analysis/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [7]:
theme_list = ["friendship","hope","sacrifice","battle","self development","betrayal","love","dialogue"]

In [8]:
theme_classifier(
    "I gave him a right hook then a left jab",
    theme_list,
    multi_label=True
)

{'sequence': 'I gave him a right hook then a left jab',
 'labels': ['battle',
  'self development',
  'hope',
  'sacrifice',
  'dialogue',
  'betrayal',
  'love',
  'friendship'],
 'scores': [0.9121248126029968,
  0.47499746084213257,
  0.08781782537698746,
  0.04499980807304382,
  0.020132731646299362,
  0.012040265835821629,
  0.004292320925742388,
  0.0028172561433166265]}

# Load Dataset

In [9]:
files = glob('../data/Subtitles/*.ass')

In [10]:
files[:5]

['../data/Subtitles/Naruto Season 7 - 177.ass',
 '../data/Subtitles/Naruto Season 2 - 40.ass',
 '../data/Subtitles/Naruto Season 1 - 23.ass',
 '../data/Subtitles/Naruto Season 6 - 156.ass',
 '../data/Subtitles/Naruto Season 4 - 96.ass']

In [11]:
with open(files[0],'r') as file:
    lines = file.readlines()
    lines = lines[27:]
    lines =  [ ",".join(line.split(',')[9:])  for line in lines ]

In [12]:
lines[:2]

['I want to try and gather\\Nthe unrestrained winds\n',
 'I’ll run toward the horizon,\\Nalongside the wave crests\n']

In [13]:
lines = [ line.replace('\\N',' ') for line in lines]

In [14]:
lines[:2]

['I want to try and gather the unrestrained winds\n',
 'I’ll run toward the horizon, alongside the wave crests\n']

In [15]:
" ".join(lines[:10])

'I want to try and gather the unrestrained winds\n I’ll run toward the horizon, alongside the wave crests\n I’ve made my decision,\n even if there’s a long way to go on that road.\n I’ll continue towards the future I’ve planned\n Time rushes us The heartbeat speeds up\n When I woke in the middle of a dream I kept searching for that same light\n Under the shining star-lit sky with countless constellations and shadows\n There was something beyond that… What were you gazing at?\n What were you gazing at?\n'

In [16]:
int(files[0].split('-')[-1].split('.')[0].strip())

177

In [17]:
def load_subtitles_dataset(dataset_path):
    subtitles_paths = glob(dataset_path+'/*.ass')

    scripts=[]
    episode_num=[]

    for path in subtitles_paths:

        #Read Lines
        with open(path,'r') as file:
            lines = file.readlines()
            lines = lines[27:]
            lines =  [ ",".join(line.split(',')[9:])  for line in lines ]
        
        lines = [ line.replace('\\N',' ') for line in lines]
        script = " ".join(lines)

        episode = int(path.split('-')[-1].split('.')[0].strip())

        scripts.append(script)
        episode_num.append(episode)

    df = pd.DataFrame.from_dict({"episode":episode_num, "script":scripts })
    return df

In [18]:
dataset_path = "../data/Subtitles"
df = load_subtitles_dataset(dataset_path)

In [19]:
df.head()

   episode                                             script
0      177  I want to try and gather the unrestrained wind...
1       40  Press down hard on the gas\n That’s right, the...
2       23  C'mon!\n Running like a fugitive,\n Being chas...
3      156  I want to try and gather the unrestrained wind...
4       96  We are Fighting Dreamers aiming high\n Fightin...

Run Model

In [20]:
script = df.iloc[0]['script']

In [21]:
script

'I want to try and gather the unrestrained winds\n I’ll run toward the horizon, alongside the wave crests\n I’ve made my decision,\n even if there’s a long way to go on that road.\n I’ll continue towards the future I’ve planned\n Time rushes us The heartbeat speeds up\n When I woke in the middle of a dream I kept searching for that same light\n Under the shining star-lit sky with countless constellations and shadows\n There was something beyond that… What were you gazing at?\n What were you gazing at?\n I’m exhausted!\n Important solo mission, my butt!\n They just didn’t have enough manpower for the castle restoration.\n That’s not the job of a Shinobi.\n Ow-ow… I won’t hold up if I don’t rest somewhere.\n Oh!\n I’ll take a bath. Here I go!\n Hey… I’m sounding like an old man.\n Wh-What?!\n Shadow Clone Jutsu!\n Thank you.\n Who the heck are you, mister?\n I’m a Delivery Ninja!\n Please, Mr. Postman!\n 23, 24, 25…\n 26…\n No mistake…\n Thanks to you Mister Naruto, all of the postal articles are safe.\n By the way, what’s a Delivery Ninja?\n We are postal professionals who risk our lives\n to deliver the important parcels our customers have left with us.\n In other words, you’re a postman.\n I am a Delivery Ninja!\n Ordinary postmen don’t risk their lives.\n So you’re an awesome postman, huh?\n That’s right.\n Oops, I must not keep my customers waiting.\n Then, I’ll be on my way…\n Mister! What’s your name?!\n I’m 596-03.\n A zip code…?!\n Anywhere would be fine if I can get in a hot spring…\n Cripes… Here it’s still day time and…\n That voice…\n My, you’re a strange one, Jira-chan.\n Am I?\n Ah, Pervy Sage!\n What?! Who’s a Pervy Sage…?!\n What’s the meaning of this, Pervy Sage?!\n Hadn’t you left the village on an important mission?\n That’s why I was being patient about you training with me!\n If you’ve got the free time to be doing something like this,\n help out with my training right now!\n W-Wait, Naruto. There’s a reason for this…\n You probably have some glib lies about gathering information or something.\n You’re wrong, you’re wrong. lt’s data collection, data collection…\n You see…\n It’s my final spurt\n for the manuscript of the final volume of “Make-Out Violence.”\n What about the mission…?\n Well, you see, I’m on a mission.\n So don’t worry…\n What kind of mission?\n As it happens, I received information that a member of the Akatsuki Organization\n will be visiting this town the day after tomorrow.\n The Akatsuki Organization! Then, that Itachi will be…?\n I don’t know that. And the same goes for their purpose…\n But that’s a matter until the day after tomorrow.\n And so, I’m making effective use of the free time!\n Then it’s perfect. Give me some training!\n Well… you see, they’re so insistent about the manuscript.\n I ended up promising the publisher that I’d send it today or tomorrow.\n Come on! It’s a long-awaited chance for training.\n If my manuscript were to be completed early,\n I might be able to take some time for training.\n Oh, my shoulders are stiff!\n There, there.\n Oh, I’m thirsty!\n Here you go.\n Hot!\n Hey, the ideas I just about had have blown away!\n Enough!\n I’m taking a bath!\n What a hard Sensei to please…\n I bet he’s going to say this is data collection, anyway.\n We must deliver that secret document\n to the feudal lord of the Land of Fangs, no matter what the cost…\n It seems this is where the Delivery Ninjas always stay.\n Oh, they could…\n Delivery Ninja?\n I can see them now.\n This is all I need for my writing desire to well up…\n I’m not getting…inspired with this…\n Imagining with your head is a writer’s job, isn’t it?\n I’m a writer rooted in realism! Getting a picture is important.\n So I wonder if you’d do that for me.\n Can you write if I do that?\n I’ll write, I’ll write!\n Sexy Jutsu: Steam Bath Harem Version!\n – Master Jiraiya. Jiraiya! – This is great!\n Won-der-ful!\n What a hopeless guy!\n He hasn’t been able to write at all!\n Address, check! Zip code, check--!\n Ow-ow-ow…\n Oh, the sealed documents…\n Please take extra care with this.\n I will take it for you.\n Ow-ow-ow…\n Excuse me, can I also ask you to take this for me?\n Oh! Mister Naruto. Thank you for helping me out yesterday.\n Oh! Mister!\n I am 596-03.\n It’s hard to remember!\n More importantly, I want to ask you to take care of this!\n Hmm…This goes in a different direction…\n Have a heart. Please.\n Oh, perfect timing.\n Huh?! Is this a Shadow Clone?\n He is 463-72.\n This area should be in your jurisdiction.\n It is.\n Then I leave it to you… What was it again?\n I am 463-72.\n Hurry, okay?\n Wake up…\n Whoa! I fell asleep!\n Pervy Sage, let’s start training!\n What’re you talking about? I must complete the manuscript…\n You don’t need to worry about that.\n I wrote the manuscript and sent it to the publisher!\n So now you can devote yourself freely to training…\n Right, Pervy Sage?\n You idiot!\n Huh?\n If something like this were read, it’ll be the end of my writing career!\n Ah… Oh… I’m sorry.\n You said you sent it to the publisher, right? How?\n I gave it to a Delivery Ninja in the inn…\n D-Delivery Ninjas.\n You mean, the one that delivers any parcel to the addressee, no matter what…\n not influenced by any land or institution… that iron organization?!\n After him, Naruto.\n We’ll chase down the Delivery Ninja, no matter what…\n and retrieve your manuscript at any cost!\n If he’s going to the publisher, he should definitely take this path.\n Now what’s left is how to close the time gap…\n I hear the leg power of Delivery Ninjas is extraordinary, though…\n Pervy Sage!\n Slow down the pace a little, man.\n Naruto! This is also training!\n To be straight, you’re short on leg power!\n A Ninja must apply oneself,\n connecting this with training, no matter what the situation!\n Excellent, Pervy Sage. Now you’re talking!\n It’s just like a maze!\n We’re totally lost…\n If we had Hinata’s or Neji’s Byakugan at a time like this…\n Byakugan! I didn’t think of that!\n That’s the Rasengan, isn’t it?!\n I’m sorry!\n Uh, no, you see…!\n This isn’t the time to be drooling!\n There he is!\n After him, Naruto.\n R-Right!\n Thieves!\n Hey, wait!\n There’s no fool who’d wait after being told to wait!\n As it happens,\n the parcel this person here left with you this morning is a slip-up!\n That’s right!\n I have no knowledge of that.\n The rule for us Delivery Ninjas\n is to deliver parcels once left with us to the destination,\n even if we have to risk our lives!\n My life as a writer is also at risk!\n Don’t look at me.\n This is trouble!\n Sorry.\n To do that to someone who’s doing honest work…\n Shut up! When you get right down to it, it was you who…\n Huh?! What’s this?!\n This isn’t the thing you wrote!\n Oh!\n That time! It got switched with my manuscript!\n Say what?!\n This is…a secret document directed\n to the feudal lord of the Land of Fangs from the Land of Claws…\n Let me see… According to the information I’ve gotten,\n the Fang and the Claw could go to war at any moment…\n This is a secret document for peace!\n They’ve decided on peace?! lt’s written here.\n That’s a good thing, isn’t it?! War is no good!\n You! You idiot! The fact that this secret document is here means\n the manuscript you wrote is being taken to the Land of Fangs!\n What’ll happen if they read it as a secret document\n from the Land of Claws?\n This is bad! No doubt, war will begin!\n We’re going to the Land of Fangs!\n R-Right!\n This time for sure we’ll take back the manuscript!\n Postal thieves… my customer’s important parcel…!\n This is bad!\n This is 463-72. This is 463-72!\n A postal robbery has occurred!\n The thieves are a pair,\n a large man with a perverted look and a kid!\n "They appear to be after 596-03’s parcel."\n "Members in the area are assigned to protect 596-03!"\n "Stop the thieves in the name of the Delivery Ninja!"\n The only way to get to the Land of Fangs is to go up this river.\n More than likely they will also go by boat.\n Then depending on our speed, there’s a chance we’ll catch up.\n I’m the one who’s got it rough.\n You don’t have enough physical strength!\n Consider this also as training and apply yourself!\n That again?!\n Who’re those guys?!\n It appears reinforcements have been summoned.\n Hurry, Naruto!\n Naruto! Switch places!\n Rasengan!\n Rasengan!\n Somehow…the Rasengan looks like a really cheap Jutsu…\n It’s for the sake of preventing a war!\n Our mission of peace is at stake!\n – Right! \t\t\t\t\t– Switch.\n Huh?\n Shadow Clone Jutsu!\n Rasengan!\n Rasengan!\n Rasengan!\n That’s it!\n Hey, wait! It’s a slip-up! This is the real one!\n They got switched during the commission!\n Delivery Ninja old man, it’s the truth!\n I’m sorry.\n According to our rule, we are never to look inside\n a customer’s parcel we have taken on, no matter what.\n If that passes over to the Land of Fangs,\n there will be war!\n Even if that were the case, I must not break the rule.\n You’re impossible!\n It’s the Land of Fangs!\n All we do is carry out our duties!\n Then…we’ll take it away by force if we have to.\n – Postal delivery! – Postal delivery!\n Naruto! Do you know which one it is?!\n No, I don’t!\n I am 596-03.\n I know! It’s 596-03!\n Where is he?!\n Up there!\n Naruto, you hold back the front! I’ll rout the rest!\n Got it!\n I won’t let you go past here!\n In the name of the Delivery Ninja,\n I will not let anyone interfere!\n You’re an impressive old man…\n I too, in the name of the Leaf Ninja,\n will take away the manuscript with a Jutsu!\n Let’s go!\n Harem Jutsu! Riverside Mad Dance!\n Mis-ter De-li-very Nin-ja.\n No, no! This isn’t the time to be doing something like this.\n Now, to get cracking with my delivery.\n Deliver…\n I will deliver.\n Hey, where are you going? Play with me.\n No, no! Not that way.\n I’ll do my best!\n Guys! Give me a hand!\n – Right! Yeah. \t\t\t\t\t– Okay!\n P-P-Postal delivery.\n Okay, good work.\n This guy’s iron will is the real deal…\n We’re too late, huh…?\n Is war going to start?!\n Th-This is--!\n It’s a manuscript of the latest issue of the Make-Out series!\n That Land of Claws feudal lord…!\n To think he’d know I was a big fan of the Make-Out series!\n Everyone!\n Stop the fighting!\n Send a messenger to the Land of Claws!\n Don’t let anybody in…\n I kind of don’t really get it, but… with this, there’ll be no war?\n No war is fine…\n But does this mean my writing power is the same as Naruto’s scribbling…?!\n Now then!\n Today’s the day the Akatsuki Organization guy comes!\n We’ll capture him no matter what and get information about Sasuke…\n Pervy Sage?\n Sorry, Naruto. There was a development while you were sleeping.\n I will pursue the Akatsuki Organization as is.\n I’ve been had!\n Well… I suppose it made for some good training…\n The wind blows, Ah…\n The pain, The memories won’t disappear\n What should be brought along?\n Assemble them into a piece.\n There is no second chance, never\n How foolish it is to throw away\n Acting so innocently, Ah…\n The images.\n It probably will not end\n It probably will not end\n Burn that love-filled heart,\n Sail across a thousand dreams\n Running freely\n To take hold of the world in hand\n The clouds scatter\n The sun sets yet again\n The solo parade begins to move.\n Adventure, Lucky Day, Heart Beat, Rising,\n Decisive, Encounter, Life, Mutual Love\n All right, everyone, follow me.\n Wait.\n We’re heading for the Village Hidden in Stars\n on a mission to protect a mysterious star.\n Naruto!\n Man, I’m getting fired up.\n We all need to work together here.\n Now, let’s all unite and show the boundless power of the Leaf.\n Hey, don’t be following us like it’s matter of course, Naruto.\n You’re not listed as a member for this mission.\n Next time: “Encounter! The Boy With a Star\'s Name”\n'

In [22]:
script_sentences = sent_tokenize(script)
script_sentences[:3]

['I want to try and gather the unrestrained winds\n I’ll run toward the horizon, alongside the wave crests\n I’ve made my decision,\n even if there’s a long way to go on that road.',
 'I’ll continue towards the future I’ve planned\n Time rushes us The heartbeat speeds up\n When I woke in the middle of a dream I kept searching for that same light\n Under the shining star-lit sky with countless constellations and shadows\n There was something beyond that… What were you gazing at?',
 'What were you gazing at?']

In [23]:
# Batch Sentence
sentence_batch_size=20
script_batches = []
for index in range(0,len(script_sentences),sentence_batch_size):
    sent = " ".join(script_sentences[index:index+sentence_batch_size])
    script_batches.append(sent)

In [24]:
script_batches[:2]

['I want to try and gather the unrestrained winds\n I’ll run toward the horizon, alongside the wave crests\n I’ve made my decision,\n even if there’s a long way to go on that road. I’ll continue towards the future I’ve planned\n Time rushes us The heartbeat speeds up\n When I woke in the middle of a dream I kept searching for that same light\n Under the shining star-lit sky with countless constellations and shadows\n There was something beyond that… What were you gazing at? What were you gazing at? I’m exhausted! Important solo mission, my butt! They just didn’t have enough manpower for the castle restoration. That’s not the job of a Shinobi. Ow-ow… I won’t hold up if I don’t rest somewhere. Oh! I’ll take a bath. Here I go! Hey… I’m sounding like an old man. Wh-What?! Shadow Clone Jutsu! Thank you. Who the heck are you, mister? I’m a Delivery Ninja! Please, Mr. Postman! 23, 24, 25…\n 26…\n No mistake…\n Thanks to you Mister Naruto, all of the postal articles are safe. By the way, what’s a Delivery Ninja?',
 'We are postal professionals who risk our lives\n to deliver the important parcels our customers have left with us. In other words, you’re a postman. I am a Delivery Ninja! Ordinary postmen don’t risk their lives. So you’re an awesome postman, huh? That’s right. Oops, I must not keep my customers waiting. Then, I’ll be on my way…\n Mister! What’s your name?! I’m 596-03. A zip code…?! Anywhere would be fine if I can get in a hot spring…\n Cripes… Here it’s still day time and…\n That voice…\n My, you’re a strange one, Jira-chan. Am I? Ah, Pervy Sage! What?! Who’s a Pervy Sage…?! What’s the meaning of this, Pervy Sage?! Hadn’t you left the village on an important mission? That’s why I was being patient about you training with me! If you’ve got the free time to be doing something like this,\n help out with my training right now!']

In [25]:
theme_output = theme_classifier(
    script_batches[:2],
    theme_list,
    multi_label=True
)

In [26]:
theme_output

[{'sequence': 'I want to try and gather the unrestrained winds\n I’ll run toward the horizon, alongside the wave crests\n I’ve made my decision,\n even if there’s a long way to go on that road. I’ll continue towards the future I’ve planned\n Time rushes us The heartbeat speeds up\n When I woke in the middle of a dream I kept searching for that same light\n Under the shining star-lit sky with countless constellations and shadows\n There was something beyond that… What were you gazing at? What were you gazing at? I’m exhausted! Important solo mission, my butt! They just didn’t have enough manpower for the castle restoration. That’s not the job of a Shinobi. Ow-ow… I won’t hold up if I don’t rest somewhere. Oh! I’ll take a bath. Here I go! Hey… I’m sounding like an old man. Wh-What?! Shadow Clone Jutsu! Thank you. Who the heck are you, mister? I’m a Delivery Ninja! Please, Mr. Postman! 23, 24, 25…\n 26…\n No mistake…\n Thanks to you Mister Naruto, all of the postal articles are safe. By the way, what’s a Delivery Ninja?',
  'labels': ['dialogue',
   'self development',
   'sacrifice',
   'battle',
   'hope',
   'friendship',
   'betrayal',
   'love'],
  'scores': [0.9834365248680115,
   0.7999486327171326,
   0.7867300510406494,
   0.5035982728004456,
   0.49009671807289124,
   0.3165415823459625,
   0.17679840326309204,
   0.15747353434562683]},
 {'sequence': 'We are postal professionals who risk our lives\n to deliver the important parcels our customers have left with us. In other words, you’re a postman. I am a Delivery Ninja! Ordinary postmen don’t risk their lives. So you’re an awesome postman, huh? That’s right. Oops, I must not keep my customers waiting. Then, I’ll be on my way…\n Mister! What’s your name?! I’m 596-03. A zip code…?! Anywhere would be fine if I can get in a hot spring…\n Cripes… Here it’s still day time and…\n That voice…\n My, you’re a strange one, Jira-chan. Am I? Ah, Pervy Sage! What?! Who’s a Pervy Sage…?! What’s the meaning of this, Pervy Sage?! Hadn’t you left the village on an important mission? That’s why I was being patient about you training with me! If you’ve got the free time to be doing something like this,\n help out with my training right now!',
  'labels': ['sacrifice',
   'dialogue',
   'self development',
   'friendship',
   'battle',
   'hope',
   'betrayal',
   'love'],
  'scores': [0.9604353904724121,
   0.8871626257896423,
   0.7575957179069519,
   0.3242659866809845,
   0.23251692950725555,
   0.20469118654727936,
   0.18697823584079742,
   0.11637633293867111]}]

In [27]:
# Wrangle Ouput
# battle: [0.51489498, 0.2156498]
themes = {}
for output in theme_output:
    for label,score in zip(output['labels'],output['scores']):
        if label not in themes:
            themes[label] = []
        themes[label].append(score)

In [29]:
themes

{'dialogue': [0.9834365248680115, 0.8871626257896423],
 'self development': [0.7999486327171326, 0.7575957179069519],
 'sacrifice': [0.7867300510406494, 0.9604353904724121],
 'battle': [0.5035982728004456, 0.23251692950725555],
 'hope': [0.49009671807289124, 0.20469118654727936],
 'friendship': [0.3165415823459625, 0.3242659866809845],
 'betrayal': [0.17679840326309204, 0.18697823584079742],
 'love': [0.15747353434562683, 0.11637633293867111]}

In [31]:
themes = {key: np.mean(np.array(value)) for key,value in themes.items()}

In [32]:
themes

{'dialogue': np.float64(0.9352995753288269),
 'self development': np.float64(0.7787721753120422),
 'sacrifice': np.float64(0.8735827207565308),
 'battle': np.float64(0.36805760115385056),
 'hope': np.float64(0.3473939523100853),
 'friendship': np.float64(0.3204037845134735),
 'betrayal': np.float64(0.18188831955194473),
 'love': np.float64(0.13692493364214897)}

In [33]:
def get_themes_inference(script):
    script_sentences = sent_tokenize(script)

    # Batch Sentence
    sentence_batch_size=20
    script_batches = []
    for index in range(0,len(script_sentences),sentence_batch_size):
        sent = " ".join(script_sentences[index:index+sentence_batch_size])
        script_batches.append(sent)
    
    # Run Model
    theme_output = theme_classifier(
        script_batches[:2],
        theme_list,
        multi_label=True
    )

    # Wrangle Output 
    themes = {}
    for output in theme_output:
        for label,score in zip(output['labels'],output['scores']):
            if label not in themes:
                themes[label] = []
            themes[label].append(score)

    themes = {key: np.mean(np.array(value)) for key,value in themes.items()}

    return themes

In [34]:
df = df.head(2)

In [35]:
df

   episode                                             script
0      177  I want to try and gather the unrestrained wind...
1       40  Press down hard on the gas\n That’s right, the...

In [36]:
output_themes = df['script'].apply(get_themes_inference)

In [37]:
theme_df = pd.DataFrame(output_themes.tolist())

In [38]:
theme_df

,dialogue,self development,sacrifice,battle,hope,friendship,betrayal,love
0,0.935300,0.778772,0.873583,0.368058,0.347394,0.320404,0.181888,0.136925
1,0.898511,0.671284,0.899896,0.893791,0.414528,0.120897,0.793941,0.180960

In [39]:
df[theme_df.columns] = theme_df
df

,episode,script,dialogue,self development,sacrifice,battle,hope,friendship,betrayal,love
0,177,I want to try and gather the unrestrained wind...,0.935300,0.778772,0.873583,0.368058,0.347394,0.320404,0.181888,0.136925
1,40,"Press down hard on the gas\n That’s right, the...",0.898511,0.671284,0.899896,0.893791,0.414528,0.120897,0.793941,0.180960